### PR TITLE
Feature/initial front end setup

### PR DESCRIPTION
**Pull request by nitrotap**
setting up express-handlebars
setting up login form

### CODE REVIEW

**Comment by kstensing** [comment]
Great progress!  The only thing we may want to change is having the user login with their username & password as opposed to their email and password.  We can decide as a team in class tonight.  We can always go back and change it if we decide.

**Review by kstensing — CHANGES_REQUESTED** [review]
change login in login.js file to use username & password as opposed to email & password

**Comment by nitrotap** [comment]
changed it up for username/password

**Review by kstensing — APPROVED** [review]
This looks great! Approved :)

**Pull request merged**
